# This file is a template, and might need editing before it works on your project.
image: electronuserland/builder:wine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
    - node_modules/
    - .yarn

package:
    stage: build
    variables: 
        VERSION_ID: '1.0.$CI_PIPELINE_ID'
    before_script:
        - yarn install
    script:
        - sed "s/1.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
        - yarn dist
    artifacts:
        paths:
            - $CI_PROJECT_DIR/dist/*.*
    only:
        - tags
        - web